import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export async function exportToPDF(title: string, bulletPoints: string[], description: string, productName: string) {
  // Create a temporary container with the content styled to render Chinese correctly
  const container = document.createElement('div');
  container.style.cssText = `
    position: fixed;
    left: -9999px;
    top: 0;
    width: 600px;
    padding: 40px;
    background: white;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans CJK SC', 'Microsoft YaHei', sans-serif;
    color: #1a1a1a;
  `;

  container.innerHTML = `
    <div style="text-align: center; margin-bottom: 30px;">
      <h1 style="font-size: 24px; margin: 0 0 10px 0;">Product Listing</h1>
      <p style="color: #666; margin: 0;">Generated by AI Product Content Generator</p>
    </div>
    
    <div style="margin-bottom: 25px; padding: 15px; background: #f5f5f5; border-radius: 8px;">
      <p style="margin: 0;"><strong>Product:</strong> ${productName || 'N/A'}</p>
    </div>
    
    <div style="margin-bottom: 20px;">
      <h2 style="font-size: 16px; color: #333; border-bottom: 2px solid #0066cc; padding-bottom: 8px; margin: 0 0 12px 0;">Title</h2>
      <p style="font-size: 14px; line-height: 1.6; margin: 0;">${title || 'N/A'}</p>
    </div>
    
    <div style="margin-bottom: 20px;">
      <h2 style="font-size: 16px; color: #333; border-bottom: 2px solid #0066cc; padding-bottom: 8px; margin: 0 0 12px 0;">Bullet Points</h2>
      <ul style="font-size: 14px; line-height: 1.8; padding-left: 20px; margin: 0;">
        ${bulletPoints.map((point, i) => `<li style="margin-bottom: 8px;">${point}</li>`).join('')}
      </ul>
    </div>
    
    <div style="margin-bottom: 20px;">
      <h2 style="font-size: 16px; color: #333; border-bottom: 2px solid #0066cc; padding-bottom: 8px; margin: 0 0 12px 0;">Description</h2>
      <p style="font-size: 14px; line-height: 1.8; margin: 0; white-space: pre-wrap;">${description || 'N/A'}</p>
    </div>
  `;

  document.body.appendChild(container);

  try {
    // Use html2canvas to render the container (handles CJK characters correctly)
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });

    // Create PDF and add the image
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'px',
      format: [canvas.width / 2, canvas.height / 2 + 40]
    });

    pdf.addImage(imgData, 'PNG', 0, 0, canvas.width / 2, canvas.height / 2);
    pdf.save(`product-listing-${Date.now()}.pdf`);
  } finally {
    document.body.removeChild(container);
  }
}

export function exportToCSV(title: string, bulletPoints: string[], description: string, productName: string, brandName: string) {
  // Create CSV content
  const headers = ['Product', 'Brand', 'Title', 'Bullet Points', 'Description'];
  const rows = [
    `"${(productName || '').replace(/"/g, '""')}"`,
    `"${(brandName || '').replace(/"/g, '""')}"`,
    `"${(title || '').replace(/"/g, '""')}"`,
    `"${(bulletPoints.join('; ')).replace(/"/g, '""')}"`,
    `"${(description || '').replace(/"/g, '""')}"`,
  ];

  const csvContent = [headers.join(','), rows.join(',')].join('\n');

  // Download
  const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `product-listing-${Date.now()}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
}
