import jsPDF from 'jspdf';

export function exportToPDF(title: string, bulletPoints: string[], description: string, productName: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Product Listing', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Product Name
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Product:', 20, y);
  doc.setFont('helvetica', 'normal');
  doc.text(productName || 'N/A', 50, y);
  y += 10;

  // Title Section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Title', 20, y);
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  const titleLines = doc.splitTextToSize(title || 'N/A', pageWidth - 40);
  doc.text(titleLines, 20, y);
  y += titleLines.length * 6 + 10;

  // Bullet Points Section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Bullet Points', 20, y);
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  bulletPoints.forEach((point, idx) => {
    const bulletLines = doc.splitTextToSize(`${idx + 1}. ${point}`, pageWidth - 40);
    doc.text(bulletLines, 20, y);
    y += bulletLines.length * 5 + 3;
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  y += 5;

  // Description Section
  if (y > 250) {
    doc.addPage();
    y = 20;
  }
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Description', 20, y);
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const descLines = doc.splitTextToSize(description || 'N/A', pageWidth - 40);
  doc.text(descLines, 20, y);

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(`Generated by AI Product Content Generator - Page ${i}/${pageCount}`, pageWidth / 2, 290, { align: 'center' });
  }

  doc.save(`product-listing-${Date.now()}.pdf`);
}

export function exportToCSV(title: string, bulletPoints: string[], description: string, productName: string, brandName: string) {
  // Create CSV content
  const headers = ['Product', 'Brand', 'Title', 'Bullet Points', 'Description'];
  const rows = [
    `"${(productName || '').replace(/"/g, '""')}"`,
    `"${(brandName || '').replace(/"/g, '""')}"`,
    `"${(title || '').replace(/"/g, '""')}"`,
    `"${(bulletPoints.join('; ')).replace(/"/g, '""')}"`,
    `"${(description || '').replace(/"/g, '""')}"`,
  ];

  const csvContent = [headers.join(','), rows.join(',')].join('\n');

  // Download
  const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `product-listing-${Date.now()}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
}
